# Generated by Django 4.0.4 on 2022-05-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='city',
            field=models.CharField(default='a', max_length=80),
            preserve_default=False,
        ),
    ]
